# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "larray-editor" %}
{% set version = "0.1" %}
{% set sha256 = "xxx" %}
# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/larray-project/larray-editor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  # script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  build:
    - python
    # When setuptools is available add the `--single-version-externally-managed --record record.txt` above.
    # - setuptools
    # if your project compiles code (such as a C extension) then add `toolchain` as a build requirement.
    - larray
    - pytest-runner
  run:
    - python
    - larray
    - matplotlib
    - pyqt
    - qtpy
    - pytest-runner

#test:
#  # Some package might need a `test/commands` key to check CLI.
#  # List all the packages/modules that `run_test.py` imports.
#  imports:
#    - simplejson
#    - simplejson.tests

about:
  home: https://github.com/larray-project/larray-editor
  # Remember to specify the license variants for BSD, Apache, GPL, and LGLP.
  # Prefer the short version, e.g: GPL-2.0 instead of GNU General Public License version 2.0
  # See https://opensource.org/licenses/alphabetical
  license: GPL-3.0
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: GPL
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See http://conda.pydata.org/docs/building/meta-yaml.html#license-file
  license_file: LICENSE
  summary: 'Graphical user interface associated with larray package'

  # The remaining entries in this section are optional, but recommended
  description: |
    Graphical user interface associated with larray package
  doc_url: http://larray.readthedocs.io/
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - alixdamman
    - gdementen
